Vagrant.configure("2") do |config|
    # Servidor Apache 1
    config.vm.define "apache1" do |apache1|
      apache1.vm.box = "ubuntu/bionic64"
      apache1.vm.hostname = "apache1"
      apache1.vm.network "private_network", ip: "192.168.33.10"
      apache1.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      # Directorio compartido con la máquina local
      apache1.vm.synced_folder "./src", "/var/www/html", type: "virtualbox"
      apache1.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo systemctl enable apache2
        sudo systemctl start apache2
      SHELL
    end
  
    # Servidor Apache 2
    config.vm.define "apache2" do |apache2|
      apache2.vm.box = "ubuntu/bionic64"
      apache2.vm.hostname = "apache2"
      apache2.vm.network "private_network", ip: "192.168.33.11"
      apache2.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      apache2.vm.synced_folder "./src", "/var/www/html", type: "virtualbox"
      apache2.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo systemctl enable apache2
        sudo systemctl start apache2
      SHELL
    end
  
    # Servidor Nginx (Balanceador de carga)
    config.vm.define "nginx" do |nginx|
      nginx.vm.box = "ubuntu/bionic64"
      nginx.vm.hostname = "nginx"
      nginx.vm.network "private_network", ip: "192.168.33.12"
      nginx.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      nginx.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
        # Eliminar la configuración por defecto
        sudo rm /etc/nginx/sites-enabled/default
        # Crear configuración de balanceo de carga
        cat <<EOF | sudo tee /etc/nginx/sites-available/load_balancer
  upstream backend {
      server 192.168.33.10;
      server 192.168.33.11;
  }
  
  server {
      listen 80 default_server;
      location / {
          proxy_pass http://backend;
      }
  }
  EOF
        sudo ln -s /etc/nginx/sites-available/load_balancer /etc/nginx/sites-enabled/
        sudo systemctl restart nginx
      SHELL
    end
  end
  